#!/bin/bash

set -e
# Set the environment to development by default.
if [ -z "$DEV_MODE" ]; then
  export DEV_MODE=false
fi

build_node() { 
	echo -e "Building Angular app"
	echo -e "Environment: \n\tDEV_MODE=${DEV_MODE}"
	if [ "$DEV_MODE" == true ]; then
		echo "Building development mode..."
		exec ng build
	  else
		echo "Launching via npm..."
		exec ng build --prod
	fi
	mv dist /var/www
}

run_nginx() { 

}


# Allow debugging the builder image itself, by using:
# $ docker run -it bucharestgold/centos-s2i-nodejs --debug
#
[ "$1" == "--debug" ] && exec /bin/bash

build_node
